language: go
go:
- '1.10'
install: go get github.com/google/go-containerregistry/cmd/ko
matrix:
  include:
  - stage: test
    sudo: required
    services:
    - docker
    script:
    - go test ./...
    - ko resolve -L -f config/
  - stage: publish
    sudo: required
    env:
    - TASK=docker-push
    services:
    - docker
    script: "./.travis.docker-push.sh"
  - stage: fats
    script: "curl -s -L https://github.com/projectriff/fats/raw/master/.travis.fats-trigger.sh | bash"
stages:
- test
- name: publish
  if: branch = master AND type = push
- name: fats
  if: branch = master AND type = push
notifications:
  slack:
    secure: jLnQxf4jQJu//9YETPUQx+haEXZPahOb7VeQmBmOP9A7cPh1j/tFwJFf4ZX5C+cjBEsVeUz7PHHu439v8jxvZ/kZXxC6y957qyangGo2SoFe/BWdfKSH5zHjrjSQ0Yl948mdRYo6PrSfb2XBlAbH+DWOWAELiSQU69LVpv3jaWk5BQDTF0QIchyRqWaLoVEFArCRhGBzj7w0dCeZYC4cBp7AHNLsUWcbBr4CRWq7aVPIPF+mFNjiwdU4cuVNLszqn46o2ECsofpc/39yrDOL4FYfeynX4f8Ssg8AHHEPSmrMvSMIWXYzaw80kwKx9xw0KsdnUoESCP42YTVC4WEz8zJJJlKUAPJxlUjEb7lSB6LzckfSErJv4TCI7yXUIB8s1PvkGRc0w5DQrzw7WXisQzefgbjzvjxs7Wc2oFJ0jbNAFzeyWT5qaalgj+S8MzDOmgrm6RVdH8SRs3dJsuntLsPtU2C/bzdzvo90Q7kjzKsJdJvPmVnqvw7mN6i20EReLJREIFSap78LdItZSPRF2NqWUbN2zD8xmnZwLis2XquhB9jJu8X9kX6iLGRDqgB3u8HgG2fK37dGci5edqw/3XFNcJk9TDHSCV0ZqT873Q49Rd4HPK0eAnI63c444tEhtUl9fGssDRObRKyU0zw3plaXVy+T7Bao19gUnPUsBEA=
